version: '3.8'

services:
  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_USER: trackerman
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: tracker
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - habit-tracker-network

  habit-tracker-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: habit-tracker-app
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/tracker
      SPRING_DATASOURCE_USERNAME: trackerman
      SPRING_DATASOURCE_PASSWORD: 123456
    ports:
      - "8080:8080"
    networks:
      - habit-tracker-network

volumes:
  postgres-data:

networks:
  habit-tracker-network: